import Foundation

public enum ConversationField: String, Codable, Hashable, CaseIterable, Sendable {
    case category = "Category"
    case firstResponseTime = "FirstResponseTime"
    case handleTime = "HandleTime"
    case humanAgents = "HumanAgents"
    case humanAgentsWithInserts = "HumanAgentsWithInserts"
    case app = "App"
    case sentiment = "Sentiment"
    case qualityReason = "QualityReason"
    case resolutionStatus = "ResolutionStatus"
    case resolvedByMaven = "ResolvedByMaven"
    case quality = "Quality"
    case users = "Users"
    case responseLength = "ResponseLength"
    case thumbsUpCount = "ThumbsUpCount"
    case thumbsDownCount = "ThumbsDownCount"
    case insertCount = "InsertCount"
    case tags = "Tags"
    case userMessageCount = "UserMessageCount"
    case languages = "Languages"
    case actions = "Actions"
    case incompleteActions = "IncompleteActions"
    case sources = "Sources"
    case createdAt = "CreatedAt"
    case predictedNps = "PredictedNPS"
    case organizationId = "OrganizationId"
    case agentId = "AgentId"
    case inboxItems = "InboxItems"
}