import Foundation

public struct IntelligentFieldValueSearchRequest: Codable, Hashable, Sendable {
    /// Page number to return, defaults to 0
    public let page: Int?
    /// The size of the page to return, defaults to 20. Max 1000.
    public let size: Int?
    /// Whether to sort descending, defaults to true
    public let sortDesc: Bool?
    /// Filter by properties of the intelligent field definition. If not provided, returns values for all fields.
    public let fieldFilter: IntelligentFieldValueFieldFilter?
    /// Filter by properties of the target entity. If not provided, returns values across all entities.
    public let entityFilter: IntelligentFieldValueEntityFilter?
    /// Filter values computed on or after this timestamp
    public let createdAfter: Date?
    /// Filter values computed on or before this timestamp
    public let createdBefore: Date?
    /// Whether to include results where the LLM could not determine a value (value is null). Defaults to false.
    public let includeUnknownValues: Bool?
    /// Field to sort by. Defaults to CREATED_AT.
    public let sort: IntelligentFieldValueSortField?
    /// Filter to values generated by a specific agent variant. If not provided, returns values from all variants.
    public let variantId: EntityIdWithoutAgent?
    /// Additional properties that are not explicitly defined in the schema
    public let additionalProperties: [String: JSONValue]

    public init(
        page: Int? = nil,
        size: Int? = nil,
        sortDesc: Bool? = nil,
        fieldFilter: IntelligentFieldValueFieldFilter? = nil,
        entityFilter: IntelligentFieldValueEntityFilter? = nil,
        createdAfter: Date? = nil,
        createdBefore: Date? = nil,
        includeUnknownValues: Bool? = nil,
        sort: IntelligentFieldValueSortField? = nil,
        variantId: EntityIdWithoutAgent? = nil,
        additionalProperties: [String: JSONValue] = .init()
    ) {
        self.page = page
        self.size = size
        self.sortDesc = sortDesc
        self.fieldFilter = fieldFilter
        self.entityFilter = entityFilter
        self.createdAfter = createdAfter
        self.createdBefore = createdBefore
        self.includeUnknownValues = includeUnknownValues
        self.sort = sort
        self.variantId = variantId
        self.additionalProperties = additionalProperties
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.page = try container.decodeIfPresent(Int.self, forKey: .page)
        self.size = try container.decodeIfPresent(Int.self, forKey: .size)
        self.sortDesc = try container.decodeIfPresent(Bool.self, forKey: .sortDesc)
        self.fieldFilter = try container.decodeIfPresent(IntelligentFieldValueFieldFilter.self, forKey: .fieldFilter)
        self.entityFilter = try container.decodeIfPresent(IntelligentFieldValueEntityFilter.self, forKey: .entityFilter)
        self.createdAfter = try container.decodeIfPresent(Date.self, forKey: .createdAfter)
        self.createdBefore = try container.decodeIfPresent(Date.self, forKey: .createdBefore)
        self.includeUnknownValues = try container.decodeIfPresent(Bool.self, forKey: .includeUnknownValues)
        self.sort = try container.decodeIfPresent(IntelligentFieldValueSortField.self, forKey: .sort)
        self.variantId = try container.decodeIfPresent(EntityIdWithoutAgent.self, forKey: .variantId)
        self.additionalProperties = try decoder.decodeAdditionalProperties(using: CodingKeys.self)
    }

    public func encode(to encoder: Encoder) throws -> Void {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try encoder.encodeAdditionalProperties(self.additionalProperties)
        try container.encodeIfPresent(self.page, forKey: .page)
        try container.encodeIfPresent(self.size, forKey: .size)
        try container.encodeIfPresent(self.sortDesc, forKey: .sortDesc)
        try container.encodeIfPresent(self.fieldFilter, forKey: .fieldFilter)
        try container.encodeIfPresent(self.entityFilter, forKey: .entityFilter)
        try container.encodeIfPresent(self.createdAfter, forKey: .createdAfter)
        try container.encodeIfPresent(self.createdBefore, forKey: .createdBefore)
        try container.encodeIfPresent(self.includeUnknownValues, forKey: .includeUnknownValues)
        try container.encodeIfPresent(self.sort, forKey: .sort)
        try container.encodeIfPresent(self.variantId, forKey: .variantId)
    }

    /// Keys for encoding/decoding struct properties.
    enum CodingKeys: String, CodingKey, CaseIterable {
        case page
        case size
        case sortDesc
        case fieldFilter
        case entityFilter
        case createdAfter
        case createdBefore
        case includeUnknownValues
        case sort
        case variantId
    }
}